# ========================================================
# .github/actions/build-package/action.yml
# ========================================================
# Project Name: Python Template Repository
# Description: This action builds the package
#              and uploads the resulting artifact.
#
# Usage: Include this action in workflows to build a package.
#        - name: Build Package
#          uses: ./.github/actions/build-package
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Author's GitHub Username: @Jekwwer
#
# Date: 2024-08-13
# ========================================================

name: "Build Package"
description: "Build the poject package and upload the artifact."
author: "Evgenii Shiliaev (@Jekwwer)"

runs:
  using: "composite"
  steps:
    - name: Retrieve Tag
      id: retrieve_tag
      uses: ./.github/actions/retrieve-tag

    - name: Build Package using Makefile
      run: make build-package
      shell: bash

    - name: Check Build Success
      if: ${{ success() }}
      run: echo "Build succeeded."
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{ github.ref_name }}-${{ steps.retrieve_tag.outputs.package_name }}-${{ github.run_number }}"
        path: dist/*.whl
# ========================================================
# End of .github/actions/build-package/action.yml
# ========================================================
