# ========================================================
# .github/actions/build-package/action.yml
# ========================================================
# Project Name: Python Template Repository
# Description: This action builds the package
#              and uploads the resulting artifact.
#
# Usage: Include this action in workflows to build a package.
#        - name: Build Package
#          uses: ./.github/actions/build-package
#          with:
#            name: "your-package-name" # Required
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Author's GitHub Username: @Jekwwer
#
# Date: 2024-08-14
# ========================================================

name: "Build Package"
description: "Build the poject package and upload the artifact."
author: "Evgenii Shiliaev (@Jekwwer)"

inputs:
  name:
    description: "The name of the package to build."
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Build Package using Makefile
      run: make build-package
      shell: bash

    - name: Check Build Success
      if: ${{ success() }}
      run: echo "Build succeeded."
      shell: bash

    - name: Upload Package as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.name }}"
        path: dist/*.whl
# ========================================================
# End of .github/actions/build-package/action.yml
# ========================================================
