# .github/dependabot.yml: Automates dependency updates.

# Assigns reviewers and assignees, limits open pull requests,
# and prefixes commits for better traceability.

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "GITHUB_USERNAME"
    assignees:
      - "GITHUB_USERNAME"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: ".github"
    schedule:
      interval: "weekly"
    reviewers:
      - "GITHUB_USERNAME"
    assignees:
      - "GITHUB_USERNAME"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
