# ========================================================
# sonar-project.properties
# ========================================================
# Project Name: Python Template Repository
# Description: Configuration file for SonarQube analysis.
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Date: 2024-07-24
# ========================================================

# Required project settings
sonar.projectKey=jekwwer-python-template
sonar.projectName=Python Template Repository
sonar.organization=jekwwer
sonar.projectVersion=0.1.0
sonar.python.version=3.10
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8

# ========================================================
# End of sonar-project.properties
# ========================================================
