# ========================================================
# tox.ini
# ========================================================
# Project Name: Python Template Repository
# Description: Configuration file for Tox, a generic virtualenv
#              management and test command line tool.
#
# Usage: Tox is used to automate testing in isolated environments.
#        It creates virtual environments, installs dependencies,
#        and runs test commands as specified.
#
# Run it using:
# make test
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Date: 2024-07-29
# ========================================================

[tox]
envlist = py310
skipsdist = True

[testenv]
deps =
    coverage
    pytest
    pytest-benchmark
    pytest-cov
    pytest-xdist
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    coverage run -m pytest --junitxml=reports/xunit-result.xml --benchmark-save=benchmark
    coverage xml -o reports/coverage.xml

[coverage:run]
relative_files = True
source = src/
branch = True

# ========================================================
# End of tox.ini
# ========================================================
