# ========================================================
# tox.ini
# ========================================================
# Project Name: Python Template Repository
# Description: Configuration file for Tox, a generic virtualenv
# management and test command line tool.
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Date: 2024-07-25
# ========================================================

[tox]
envlist = py310
skipsdist = True

[testenv]
deps =
    pytest
    coverage
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    coverage run -m pytest
    coverage xml -o reports/coverage.xml

[coverage:run]
relative_files = True
source = src/
branch = True

# ========================================================
# End of tox.ini
# ========================================================
