# ========================================================
# .github/actions/upload-logs-and-reports/action.yml
# ========================================================
# Project Name: Python Template Repository
# Description: This action uploads reports and logs as artifacts.
#
# Usage: Include this action in workflows to upload reports and logs:
#        - name: Upload Logs and Reports
#          uses: ./.github/actions/upload-logs-and-reports
#          with:
#            reports_path: "your-reports-path"
#                 Default: "reports/*"
#            logs_path: "your-logs-path"
#              Default: "logs/*"
#            reports_artifact_name: "your-reports-artifact-name"
#                          Default: "reports-${{ github.run_number }}"
#            logs_artifact_name: "your-logs-artifact-name"
#                        Default: "logs-${{ github.run_number }}"
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Author's GitHub Username: @Jekwwer
#
# Date: 2024-08-14
# ========================================================

name: "Upload Logs and Reports"
description: "An action to upload logs and reports as artifacts."
author: "Evgennii Shiliaev (@Jekwwer)"

inputs:
  reports_path:
    description: "The path to the reports"
    required: true
    type: string
    default: "reports/*"
  logs_path:
    description: "The path to the logs"
    required: true
    type: string
    default: "logs/*"
  reports_artifact_name:
    description: "Custom name for the reports artifact"
    required: false
    type: string
    default: "reports-${{ github.run_number }}"
  logs_artifact_name:
    description: "Custom name for the logs artifact"
    required: false
    type: string
    default: "logs-${{ github.run_number }}"

runs:
  using: "composite"
  steps:
    - name: Validate Reports Path
      run: |
        if [ -z "$(ls -A ${{ inputs.reports_path }})" ]; then
          echo "No reports found at path ${{ inputs.reports_path }}";
          exit 1;
        fi
      shell: bash

    - name: Validate Logs Path
      run: |
        if [ -z "$(ls -A ${{ inputs.logs_path }})" ]; then
          echo "No logs found at path ${{ inputs.logs_path }}";
          exit 1;
        fi
      shell: bash

    - name: Upload Reports
      if: success() || always() # Upload reports even if the job fails
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.reports_artifact_name }}
        path: ${{ inputs.reports_path }}

    - name: Upload Logs
      if: success() || always() # Upload logs even if the job fails
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.logs_artifact_name }}
        path: ${{ inputs.logs_path }}
# --------------------------------------------------------
# End of .github/actions/upload-logs-and-reports/action.yml
# --------------------------------------------------------
