# ========================================================
# .github/actions/retrieve-tag/action.yml
# ========================================================
# Project Name: Python Template Repository
# Description: Retrieves the most recent Git tag,
#              defaults to "dev" with a timestamp if none,
#              and appends "_dev" with a timestamp
#              if the tag isn't the latest.
#
# Usage: Include this action in workflows to retrieve the last Git tag.
#        - name: Retrieve Tag
#          uses: ./.github/actions/retrieve-tag
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Author's GitHub Username: @Jekwwer
#
# Date: 2024-08-17
# ========================================================

name: "Retrieve Tag"
description: >
  Retrieves the most recent Git tag.
  If no tag exists, it defaults to "dev" with a timestamp.
  If the tag isn't the latest, it appends "_dev" with a timestamp.
author: "Evgennii Shiliaev (@Jekwwer)"
runs:
  using: "composite"
  steps:
    - name: Fetch All Tags
      run: |
        git fetch --tags --force
      shell: bash

    - name: Retrieve or Generate Tag
      id: retrieve_or_generate_tag
      run: |
        # Determine if the current event is a push of a tag
        if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref_type }}" = "tag" ]; then
          TAG_NAME="${{ github.ref_name }}"
        else
          # Get the latest tag in the repository
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null)

          # Get the last commit short hash and timestamp
          LAST_COMMIT=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

          if [ -n "$LATEST_TAG" ]; then
            # If there is a tag, append _dev and timestamp
            TAG_NAME="${LATEST_TAG}_dev_${LAST_COMMIT}_${TIMESTAMP}"
          else
            # If there are no tags, use "dev" with the timestamp
            TAG_NAME="dev_${LAST_COMMIT}_${TIMESTAMP}"
          fi
        fi

        echo "Resolved Tag Name: $TAG_NAME"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
      shell: bash

outputs:
  tag:
    description: "The resolved tag name."
    value: ${{ steps.retrieve_or_generate_tag.outputs.tag }}
# ========================================================
# End of .github/actions/retrieve-tag/action.yml
# ========================================================
