# ========================================================
# .github/actions/download-logs-and-reports/action.yml
# ========================================================
# Project Name: Python Template Repository
# Description: This action downloads reports and logs as artifacts.
#
# Usage: Include this action in workflows to download reports and logs:
#        - name: Download Logs and Reports
#          uses: ./.github/actions/download-logs-and-reports
#          with:
#            reports_name: "your-reports-artifact-name"
#            logs_name: "your-logs-artifact-name"
#            download_path: "your-download-path" # Default: "artifacts/"
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Author's GitHub Username: @Jekwwer
#
# Date: 2024-08-14
# ========================================================

name: "Download Logs and Reports"
description: "An action to download logs and reports as artifacts."
author: "Evgenii Shiliaev (@Jekwwer)"

inputs:
  reports_name:
    description: "The name of the reports artifact to be downloaded."
    required: true
    type: string

  logs_name:
    description: "The name of the logs artifact to be downloaded."
    required: true
    type: string

  download_path:
    description: "The root path where the artifacts should be downloaded. Default is 'artifacts/'."
    required: false
    type: string
    default: "artifacts/"

outputs:
  reports_path:
    description: "The full path to the downloaded reports."
  logs_path:
    description: "The full path to the downloaded logs."

runs:
  using: "composite"
  steps:
    - name: Ensure Download Directory Exists
      run: mkdir -p ${{ inputs.download_path }}/reports ${{ inputs.download_path }}/logs
      shell: bash

    - name: Download Reports
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.reports_name }}
        path: ${{ inputs.download_path }}/reports

    - name: Download Logs
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.logs_name }}
        path: ${{ inputs.download_path }}/logs

    - name: Set Outputs
      run: |
        echo "reports_path=${{ inputs.download_path }}/reports" >> $GITHUB_ENV
        echo "logs_path=${{ inputs.download_path }}/logs" >> $GITHUB_ENV
      shell: bash
# --------------------------------------------------------
# End of .github/actions/download-logs-and-reports/action.yml
# --------------------------------------------------------
