# ========================================================
# .github/workflows/build.yml
# ========================================================
# Project Name: Python Template Repository
# Description: This workflow on every push or pull request event:
#                 - checks out the code,
#                 - sets up the Python environment,
#                 - runs security analysis,
#                 - runs type analysis,
#                 - lints the code,
#                 - runs tests,
#                 - performs SonarCloud analysis,
#                 - retrieves the tag,
#                 - builds the package,
#                 - uploads logs and reports.
#
# Usage: Push or pull request to trigger the build workflow.
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Author's GitHub Username: @Jekwwer
#
# Date: 2024-08-13
# ========================================================

name: Project Building

# Trigger the workflow on call from another workflow, push, or pull request
on: [workflow_call, push, pull_request]

jobs:
  build:
    name: Project Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Format Code
        uses: ./.github/actions/format

      - name: Security Analysis
        uses: ./.github/actions/security-analysis

      - name: Type Analysis
        uses: ./.github/actions/type-analysis

      - name: Lint
        uses: ./.github/actions/lint

      - name: Tests
        uses: ./.github/actions/tests

      - name: SonarCloud Analysis
        uses: ./.github/actions/sonarcloud-analysis
        with:
          github-token: ${{ secrets.SONAR_GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}

      - name: Retrieve Tag
        id: retrieve_tag
        uses: ./.github/actions/retrieve-tag

      - name: Build Package
        uses: ./.github/actions/build-package
        with:
          # Example: main-package-1.0.0-1
          name: "${{ github.ref_name }}-package-${{ steps.retrieve_tag.outputs.tag }}-${{ github.run_number }}"

      - name: Upload Logs and Reports
        uses: ./.github/actions/upload-logs-and-reports
        with:
          reports_path: "reports/*"
          logs_path: "logs/*"
          # Example: main-reports-1.0.0-1
          reports_artifact_name: "${{ github.ref_name }}-reports-${{ steps.retrieve_tag.outputs.tag }}-${{ github.run_number }}"
          logs_artifact_name: "${{ github.ref_name }}-logs-${{ steps.retrieve_tag.outputs.tag }}-${{ github.run_number }}"
# ========================================================
# End of .github/workflows/build.yml
# ========================================================
