# ========================================================
# .github/workflows/release.yml
# ========================================================
# Project Name: Python Template Repository
# Description: This workflow creates a package, and uploads
#              the package to the GitHub releases page
#              when a tag starting with "v" is pushed.
#
# Usage: Push a tag starting with "v" to trigger the release workflow.
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Author's GitHub Username: @Jekwwer
#
# Date: 2024-08-06
# ========================================================

name: Releasing

# Trigger the workflow only on push of tags starting with "v" to the main branch
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Project
    uses: ./.github/workflows/build.yml

  release:
    name: Release Package
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: package-artifact
          path: ./dist

      # Extract the tag name to use it as the release name and package version
      - name: Get Tag Name
        run: |
          TAG=${GITHUB_REF##*/}
          TAG_NO_V=${TAG#v}
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "TAG_NO_V=${TAG_NO_V}" >> $GITHUB_ENV

      - name: Find Package File
        run: |
          PACKAGE_FILE=$(ls dist/*.whl)
          echo "PACKAGE_FILE=${PACKAGE_FILE}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_github_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          draft: false
          prerelease: false

      # Upload the package to the GitHub release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_github_release.outputs.upload_url }}
          asset_path: ${{ env.PACKAGE_FILE }}
          asset_name: placeholder_package-${{ env.TAG_NO_V }}-py3-none-any.whl # TODO: Adjust the name of your package
          asset_content_type: application/octet-stream
# ========================================================
# End of .github/workflows/release.yml
# ========================================================
