# ========================================================
# .github/workflows/release.yml
# ========================================================
# Project Name: Python Template Repository
# Description: This workflow:
#              - creates a package,
#              - looks for the package artifact,
#              - retrieves the pushed tag name,
#              - creates a GitHub release,
#              - uploads the package to the GitHub releases page
#                when a tag starting with "v" is pushed.
#
# Usage: Push a tag starting with "v" to trigger the release workflow:
#        git tag -a v1.0.0 -m "Version 1.0.0"
#        git push origin v1.0.0
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Author's GitHub Username: @Jekwwer
#
# Date: 2024-08-14
# ========================================================

name: Releasing

# Trigger the workflow only on push of tags starting with "v" to the main branch
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Project
    uses: ./.github/workflows/build.yml

  release:
    name: Release Package
    runs-on: ubuntu-latest
    needs: build

    env:
      GITHUB_REF_NAME: ${{ github.ref_name }}
      RUN_NUMBER: ${{ github.run_number }}
      GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Find Artifact
        run: |
          ARTIFACT_NAME=$(gh api -H "Accept: application/vnd.github.v3+json" /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts | jq -r '.artifacts[].name' | grep -m 1 'package')
          if [ -z "$ARTIFACT_NAME" ]; then
            echo "Error: No artifact with 'package' found."
            exit 1
          fi
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
        shell: bash

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./dist

      - name: Get Pushed Tag Name
        run: |
          TAG=${GITHUB_REF##*/}
          TAG_NO_V=${TAG#v}
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "TAG_NO_V=${TAG_NO_V}" >> $GITHUB_ENV

      - name: Find Package File
        id: find_package_file
        run: |
          PACKAGE_FILE=$(ls dist/*.whl | head -n 1)
          if [ -z "$PACKAGE_FILE" ]; then
            echo "Error: No package file found in dist/."
            exit 1
          fi
          echo "PACKAGE_FILE=${PACKAGE_FILE}" >> $GITHUB_ENV
          echo "PACKAGE_BASENAME=$(basename $PACKAGE_FILE)" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_github_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_github_release.outputs.upload_url }}
          asset_path: ${{ env.PACKAGE_FILE }}
          asset_name: ${{ env.PACKAGE_BASENAME }}
          asset_content_type: application/octet-stream
# ========================================================
# End of .github/workflows/release.yml
# ========================================================
