# ========================================================
# .github/workflows/run-type-analysis.yml
# ========================================================
# Project Name: Python Template Repository
# Description: This workflow performs type analysis.
#
# Usage: This workflow is triggered by other workflows
#        to perform type analysis.
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Author's GitHub Username: @Jekwwer
#
# Date: 2024-08-10
# ========================================================

name: Type Analysis

# Trigger the workflow on call from another workflow
on: workflow_call

jobs:
  run-type-analysis:
    name: Run Type Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Type Analysis using Makefile
        run: make run-type-analysis
# ========================================================
# End of .github/workflows/run-type-analysis.yml
# ========================================================
