# ========================================================
# .github/workflows/run-tests.yml
# ========================================================
# Project Name: Python Template Repository
# Description: This workflow runs tests.
#
# Usage: This workflow is triggered by other workflows to run tests.
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Author's GitHub Username: @Jekwwer
#
# Date: 2024-08-06
# ========================================================

name: Testing

# Trigger the workflow on call from another workflow
on: workflow_call

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests using Makefile
        run: make test
# ========================================================
# End of .github/workflows/run-tests.yml
# ========================================================
