# ========================================================
# .github/workflows/run-security-analysis.yml
# ========================================================
# Project Name: Python Template Repository
# Description: This workflow performs security analysis.
#
# Usage: This workflow is triggered by other workflows
#        to run security checks.
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Author's GitHub Username: @Jekwwer
#
# Date: 2024-08-06
# ========================================================

name: Security Analysis

# Trigger the workflow on call from another workflow
on: workflow_call

jobs:
  run-security-analysis:
    name: Run Security Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Security Analysis using Makefile
        run: make security-check
# ========================================================
# End of .github/workflows/run-security-analysis.yml
# ========================================================
