# ========================================================
# .github/workflows/type-check.yml
# ========================================================
# Project Name: Python Template Repository
# Description: This workflow sets up the Python environment,
# installs dependencies, and performs type checking on push
# and pull request events.
#
# Repository: https://github.com/jekwwer/python-template
# Author: Evgenii Shiliaev
# Date: 2024-07-16
# ========================================================

name: type-check

# Trigger the workflow on push or pull request events
on: [push, pull_request]

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # TODO: Set your python version

      # Install dependencies using Makefile
      - name: Install dependencies
        run: make install-dev

      # Perform type checking using Makefile
      - name: Type check
        run: make type-check
# ========================================================
# End of .github/workflows/type-check.yml
# ========================================================
